version: 2.1
jobs:
  build:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t philmtd/golang-builder .

  release:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t philmtd/golang-builder:latest .
      - run: docker tag philmtd/golang-builder:latest philmtd/golang-builder:$CIRCLE_TAG
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push philmtd/golang-builder:latest
      - run: docker push philmtd/golang-builder:$CIRCLE_TAG

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          context:
            - dockerhub
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
